FROM jfloff/alpine-python:2.7

MAINTAINER hug33k

ENV EPITECH_API_PORT	80
ENV EPITECH_API_DEBUG	FALSE
ENV EPITECH_API_LOGGER	TRUE
ENV EPITECH_API_SLACK_TOKEN FALSE
ENV EPITECH_API_SLACK_LEVEL	FALSE

EXPOSE 80

RUN	mkdir /work

COPY	. /work/

RUN	pip install -r /work/requirements.txt

WORKDIR	/work

CMD ["python", "server.py"]
